"use client"

import { useMemo, useState } from "react"
import { Activity, FileImage, MapPin, Package, Search } from "lucide-react"

import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

type ActivityRow = { id: number; user: string; initials: string; type: string; description: string; product: string; date: string; time: string; area: string; attachment: boolean; status: "Approved" | "Pending" | "Flagged" }
const rows: ActivityRow[] = [
  { id: 1, user: "Ahmed Raza", initials: "AR", type: "Retail visit", description: "Completed merchandising and shelf audit.", product: "Classic Black Tea", date: "2026-07-21", time: "10:42 AM", area: "Gulberg III", attachment: true, status: "Approved" },
  { id: 2, user: "Sara Khan", initials: "SK", type: "Order submitted", description: "New wholesale order from Al Noor Store.", product: "Premium Basmati Rice", date: "2026-07-21", time: "10:28 AM", area: "DHA Phase 5", attachment: false, status: "Pending" },
  { id: 3, user: "Bilal Ahmed", initials: "BA", type: "Outlet check-in", description: "Arrived at assigned retail outlet.", product: "—", date: "2026-07-21", time: "10:14 AM", area: "Model Town", attachment: false, status: "Approved" },
  { id: 4, user: "Ayesha Malik", initials: "AM", type: "Product audit", description: "Inventory mismatch found during audit.", product: "Organic Green Tea", date: "2026-07-21", time: "9:56 AM", area: "Johar Town", attachment: true, status: "Flagged" },
  { id: 5, user: "Ahmed Raza", initials: "AR", type: "Client follow-up", description: "Discussed next delivery schedule.", product: "Whole Wheat Biscuits", date: "2026-07-20", time: "4:31 PM", area: "Gulberg II", attachment: false, status: "Approved" },
  { id: 6, user: "Nida Fatima", initials: "NF", type: "Retail visit", description: "Verified promotional display and pricing.", product: "Herbal Shampoo", date: "2026-07-20", time: "3:48 PM", area: "Township", attachment: true, status: "Pending" },
]

export function Activities() {
  const [date, setDate] = useState("2026-07-21"); const [user, setUser] = useState("all"); const [type, setType] = useState("all"); const [product, setProduct] = useState("all"); const [area, setArea] = useState("all"); const [query, setQuery] = useState(""); const [detailUser, setDetailUser] = useState<string | null>(null)
  const filtered = useMemo(() => rows.filter((row) => (!date || row.date === date) && (user === "all" || row.user === user) && (type === "all" || row.type === type) && (product === "all" || row.product === product) && (area === "all" || row.area === area) && `${row.user} ${row.description}`.toLowerCase().includes(query.toLowerCase())), [area, date, product, query, type, user])
  const userRows = rows.filter((row) => row.user === detailUser)
  return <main className="flex-1 bg-muted/25 p-4 sm:p-6 xl:p-8"><div className="mx-auto max-w-[1600px] space-y-5"><div><h1 className="text-2xl font-semibold tracking-tight">Activities</h1><p className="mt-1 text-sm text-muted-foreground">Review field submissions, visits, orders, and product activity.</p></div>
    <Card className="rounded-xl shadow-none"><CardContent className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-6"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search activities…" className="h-10 pl-9" /></div><Input type="date" value={date} onChange={(event) => setDate(event.target.value)} className="h-10" /><Select label="User" value={user} onChange={setUser} values={rows.map((r) => r.user)} /><Select label="Activity type" value={type} onChange={setType} values={rows.map((r) => r.type)} /><Select label="Product" value={product} onChange={setProduct} values={rows.filter((r) => r.product !== "—").map((r) => r.product)} /><Select label="Area" value={area} onChange={setArea} values={rows.map((r) => r.area)} /></CardContent></Card>
    <Card className="overflow-hidden rounded-xl shadow-none"><CardContent className="p-0"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">Activity submissions</h2><p className="mt-1 text-xs text-muted-foreground">{filtered.length} matching records</p></div><Badge variant="outline"><Activity /> Live feed</Badge></div><Table><TableHeader><TableRow><TableHead>User</TableHead><TableHead>Activity type</TableHead><TableHead>Description</TableHead><TableHead>Product</TableHead><TableHead>Submitted at</TableHead><TableHead>Location</TableHead><TableHead>Attachment</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{filtered.map((row) => <TableRow key={row.id}><TableCell><button onClick={() => setDetailUser(row.user)} className="flex items-center gap-2.5"><Avatar><AvatarFallback>{row.initials}</AvatarFallback></Avatar><span className="whitespace-nowrap font-medium">{row.user}</span></button></TableCell><TableCell className="whitespace-nowrap">{row.type}</TableCell><TableCell><p className="min-w-64 max-w-md text-muted-foreground">{row.description}</p></TableCell><TableCell><span className="flex min-w-40 items-center gap-1.5"><Package className="size-3.5 text-muted-foreground" />{row.product}</span></TableCell><TableCell className="whitespace-nowrap"><p>{row.time}</p><p className="text-xs text-muted-foreground">{row.date}</p></TableCell><TableCell><span className="flex min-w-36 items-center gap-1.5 text-muted-foreground"><MapPin className="size-3.5" />{row.area}</span></TableCell><TableCell>{row.attachment ? <Button variant="outline" size="sm"><FileImage /> View</Button> : <span className="text-xs text-muted-foreground">None</span>}</TableCell><TableCell><Badge variant={row.status === "Approved" ? "success" : row.status === "Flagged" ? "destructive" : "warning"}>{row.status}</Badge></TableCell></TableRow>)}</TableBody></Table>{!filtered.length && <div className="py-16 text-center"><Activity className="mx-auto size-8 text-muted-foreground" /><p className="mt-3 font-medium">No activities found</p></div>}</CardContent></Card></div>
    <Sheet open={detailUser !== null} onOpenChange={(open) => !open && setDetailUser(null)}><SheetContent className="w-full overflow-y-auto sm:max-w-lg"><SheetHeader className="border-b p-6"><SheetTitle>{detailUser} activity</SheetTitle><SheetDescription>Timeline and submitted activity details.</SheetDescription></SheetHeader><div className="p-6"><Tabs defaultValue="timeline"><TabsList><TabsTrigger value="timeline">Timeline</TabsTrigger><TabsTrigger value="summary">Summary</TabsTrigger></TabsList><TabsContent value="timeline"><div className="relative ml-3 border-l pl-6">{userRows.map((row) => <div key={row.id} className="relative pb-7"><span className="absolute -left-[31px] top-1 flex size-3 rounded-full border-2 border-white bg-neutral-900 ring-1 ring-border" /><div className="flex justify-between gap-3"><p className="text-sm font-medium">{row.type}</p><span className="text-xs text-muted-foreground">{row.time}</span></div><p className="mt-1 text-sm text-muted-foreground">{row.description}</p><p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground"><MapPin className="size-3" />{row.area} · {row.date}</p></div>)}</div></TabsContent><TabsContent value="summary"><div className="grid grid-cols-2 gap-3"><Summary label="Total activities" value={String(userRows.length)} /><Summary label="Approved" value={String(userRows.filter((r) => r.status === "Approved").length)} /><Summary label="Attachments" value={String(userRows.filter((r) => r.attachment).length)} /><Summary label="Areas visited" value={String(new Set(userRows.map((r) => r.area)).size)} /></div></TabsContent></Tabs></div></SheetContent></Sheet>
  </main>
}

function Select({ label, value, onChange, values }: { label: string; value: string; onChange: (value: string) => void; values: string[] }) { return <select aria-label={label} value={value} onChange={(event) => onChange(event.target.value)} className="h-10 rounded-lg border bg-background px-2.5 text-sm"><option value="all">All {label.toLowerCase()}s</option>{[...new Set(values)].map((item) => <option key={item}>{item}</option>)}</select> }
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border p-4"><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div> }
