"use client"

import { FormEvent, useState } from "react"
import {
  Bell,
  Camera,
  Check,
  Clock3,
  KeyRound,
  Laptop,
  LockKeyhole,
  Mail,
  MapPin,
  Phone,
  ShieldCheck,
  Smartphone,
  UserRound,
} from "lucide-react"

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

export function AdministratorProfile() {
  const [profileSaved, setProfileSaved] = useState(false)
  const [passwordSaved, setPasswordSaved] = useState(false)

  function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setProfileSaved(true); window.setTimeout(() => setProfileSaved(false), 2500) }
  function savePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPasswordSaved(true); event.currentTarget.reset(); window.setTimeout(() => setPasswordSaved(false), 2500) }

  return <main className="flex-1 bg-muted/25 p-4 sm:p-6 xl:p-8"><div className="mx-auto max-w-6xl space-y-5">
    <Card className="overflow-hidden rounded-xl shadow-none"><div className="h-28 bg-neutral-950 sm:h-36" /><CardContent className="relative px-5 pb-5 sm:px-8 sm:pb-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="-mt-10 flex flex-col gap-4 sm:-mt-9 sm:flex-row sm:items-end"><div className="relative w-fit"><Avatar className="size-20 border-4 border-background bg-background shadow-sm"><AvatarFallback className="bg-neutral-100 text-xl font-semibold dark:bg-neutral-800">AD</AvatarFallback></Avatar><button className="absolute -bottom-1 -right-1 flex size-7 items-center justify-center rounded-full border bg-background shadow-sm" aria-label="Change profile photo"><Camera className="size-3.5" /></button></div><div className="pb-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight">Administrator</h1><Badge variant="success">Active</Badge></div><p className="mt-1 text-sm text-muted-foreground">System Administrator · Full access</p></div></div><div className="flex gap-2"><Badge variant="outline" className="h-7"><ShieldCheck /> Verified administrator</Badge></div></div><div className="mt-6 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><ProfileMeta icon={Mail} label="Email" value="admin@example.com" /><ProfileMeta icon={Phone} label="Phone" value="+92 300 1234567" /><ProfileMeta icon={MapPin} label="Location" value="Lahore, Pakistan" /><ProfileMeta icon={Clock3} label="Member since" value="January 2024" /></div></CardContent></Card>

    <Tabs defaultValue="profile"><TabsList className="h-auto w-full justify-start overflow-x-auto p-1"><TabsTrigger value="profile" className="gap-1.5"><UserRound className="size-3.5" />Personal information</TabsTrigger><TabsTrigger value="security" className="gap-1.5"><LockKeyhole className="size-3.5" />Security</TabsTrigger><TabsTrigger value="notifications" className="gap-1.5"><Bell className="size-3.5" />Notifications</TabsTrigger><TabsTrigger value="activity" className="gap-1.5"><Clock3 className="size-3.5" />Account activity</TabsTrigger></TabsList>
      <TabsContent value="profile"><Card className="rounded-xl shadow-none"><CardContent className="p-5 sm:p-6"><div className="mb-6"><h2 className="font-semibold">Personal information</h2><p className="mt-1 text-sm text-muted-foreground">Update your administrator contact and regional preferences.</p></div>{profileSaved && <Alert variant="success" className="mb-5"><Check /><AlertTitle>Profile updated</AlertTitle><AlertDescription>Your personal information has been saved.</AlertDescription></Alert>}<form onSubmit={saveProfile} className="grid gap-5 sm:grid-cols-2"><Field label="First name" defaultValue="System" /><Field label="Last name" defaultValue="Administrator" /><Field label="Email address" type="email" defaultValue="admin@example.com" /><Field label="Phone number" defaultValue="+92 300 1234567" /><Field label="Job title" defaultValue="System Administrator" /><Field label="Office location" defaultValue="Lahore, Pakistan" /><Select label="Timezone" defaultValue="Asia/Karachi"><option>Asia/Karachi</option><option>UTC</option><option>Asia/Dubai</option></Select><Select label="Language" defaultValue="English"><option>English</option><option>Urdu</option></Select><div className="sm:col-span-2 sm:text-right"><Button type="submit">Save profile</Button></div></form></CardContent></Card></TabsContent>
      <TabsContent value="security"><div className="grid gap-5 lg:grid-cols-[1.2fr_0.8fr]"><Card className="rounded-xl shadow-none"><CardContent className="p-5 sm:p-6"><h2 className="font-semibold">Change password</h2><p className="mt-1 text-sm text-muted-foreground">Use at least eight characters with letters, numbers, and symbols.</p>{passwordSaved && <Alert variant="success" className="mt-5"><Check /><AlertTitle>Password updated</AlertTitle><AlertDescription>Your new password is now active.</AlertDescription></Alert>}<form onSubmit={savePassword} className="mt-6 space-y-5"><Field label="Current password" type="password" defaultValue="" /><Field label="New password" type="password" defaultValue="" /><Field label="Confirm new password" type="password" defaultValue="" /><Button type="submit"><KeyRound /> Update password</Button></form></CardContent></Card><div className="space-y-5"><Card className="rounded-xl shadow-none"><CardContent className="p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="text-sm font-semibold">Two-factor authentication</h2><p className="mt-1 text-xs text-muted-foreground">Add another verification step to administrator login.</p></div><Badge variant="warning">Not enabled</Badge></div><Button variant="outline" size="sm" className="mt-4">Enable 2FA</Button></CardContent></Card><Card className="rounded-xl shadow-none"><CardContent className="p-5"><h2 className="text-sm font-semibold">Active sessions</h2><Session icon={Laptop} device="Windows · Chrome" location="Lahore, Pakistan" current /><Session icon={Smartphone} device="Android · Chrome" location="Lahore, Pakistan" /><Button variant="outline" size="sm" className="mt-4 w-full">Sign out other sessions</Button></CardContent></Card></div></div></TabsContent>
      <TabsContent value="notifications"><Card className="rounded-xl shadow-none"><CardContent className="space-y-5 p-5 sm:p-6"><div className="mb-6"><h2 className="font-semibold">Personal notifications</h2><p className="mt-1 text-sm text-muted-foreground">Choose how administrator account alerts reach you.</p></div><Toggle label="Security alerts" description="New login, password change, and suspicious activity." defaultChecked /><Toggle label="Operational alerts" description="Offline users, permission issues, and flagged activities." defaultChecked /><Toggle label="Email summaries" description="Receive a daily operations summary by email." defaultChecked /><Toggle label="APK release activity" description="Release publication and download milestones." /></CardContent></Card></TabsContent>
      <TabsContent value="activity"><Card className="rounded-xl shadow-none"><CardContent className="p-5 sm:p-6"><div className="mb-6"><h2 className="font-semibold">Recent account activity</h2><p className="mt-1 text-sm text-muted-foreground">Security and administrator actions associated with your account.</p></div><div className="divide-y rounded-xl border">{[{ title: "Signed in successfully", detail: "Windows · Chrome · Lahore, Pakistan", time: "Today, 10:24 AM" }, { title: "Settings updated", detail: "Live tracking notification preferences changed", time: "Yesterday, 4:18 PM" }, { title: "APK release published", detail: "Version 2.4.0 set as active", time: "July 18, 11:05 AM" }, { title: "Password changed", detail: "Administrator account password updated", time: "June 30, 2:42 PM" }].map((item) => <div className="flex flex-col justify-between gap-2 p-4 sm:flex-row sm:items-center" key={item.title}><div><p className="text-sm font-medium">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.detail}</p></div><span className="whitespace-nowrap text-xs text-muted-foreground">{item.time}</span></div>)}</div></CardContent></Card></TabsContent>
    </Tabs>
  </div></main>
}

function ProfileMeta({ icon: Icon, label, value }: { icon: typeof Mail; label: string; value: string }) { return <div className="flex items-center gap-2.5"><span className="flex size-8 items-center justify-center rounded-lg bg-muted"><Icon className="size-3.5" /></span><span className="min-w-0"><span className="block text-[11px] text-muted-foreground">{label}</span><span className="block truncate text-xs font-medium">{value}</span></span></div> }
function Field({ label, type = "text", defaultValue }: { label: string; type?: string; defaultValue: string }) { return <label className="space-y-2 text-sm font-medium">{label}<Input type={type} defaultValue={defaultValue} required className="mt-2 h-10 font-normal" /></label> }
function Select({ label, defaultValue, children }: { label: string; defaultValue: string; children: React.ReactNode }) { return <label className="space-y-2 text-sm font-medium">{label}<select defaultValue={defaultValue} className="mt-2 h-10 w-full rounded-lg border bg-background px-2.5 font-normal">{children}</select></label> }
function Toggle({ label, description, defaultChecked = false }: { label: string; description: string; defaultChecked?: boolean }) { return <label className="flex cursor-pointer items-start justify-between gap-4"><span><span className="block text-sm font-medium">{label}</span><span className="mt-1 block text-xs text-muted-foreground">{description}</span></span><span className="relative mt-0.5 shrink-0"><input type="checkbox" defaultChecked={defaultChecked} className="peer sr-only" /><span className="block h-6 w-11 rounded-full bg-input peer-checked:bg-neutral-900 dark:peer-checked:bg-white" /><span className="absolute left-1 top-1 size-4 rounded-full bg-white shadow transition-transform peer-checked:translate-x-5 dark:peer-checked:bg-neutral-900" /></span></label> }
function Session({ icon: Icon, device, location, current = false }: { icon: typeof Laptop; device: string; location: string; current?: boolean }) { return <div className="mt-4 flex items-start gap-3"><span className="flex size-8 items-center justify-center rounded-lg bg-muted"><Icon className="size-4" /></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="text-xs font-medium">{device}</p>{current && <Badge variant="success">Current</Badge>}</div><p className="mt-1 text-[11px] text-muted-foreground">{location}</p></div></div> }
