"use client"

import { useMemo, useState } from "react"
import { Download, RefreshCw } from "lucide-react"

import { ApiError, ApiLoading } from "@/components/api-state"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { useAdminResource } from "@/hooks/use-admin-resource"
import type { AttendanceRecord } from "@/lib/api-types"

function time(value?: string) {
  return value ? new Date(value).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "—"
}

function csvCell(value: unknown) {
  return '"' + String(value ?? "").replaceAll('"', '""') + '"'
}

export function Attendance() {
  const { data, loading, error, refresh } = useAdminResource<AttendanceRecord[]>("attendance", [])
  const [date, setDate] = useState("")
  const filtered = useMemo(() => date ? data.filter((item) => item.date === date) : data, [data, date])

  function download() {
    const rows = [["Date", "Employee", "Code", "Check in", "Check out", "Minutes", "Status", "Area"], ...filtered.map((item) => [item.date, item.user?.name, item.user?.employeeCode, item.checkIn?.timestamp, item.checkOut?.timestamp, item.durationMinutes, item.status, item.area])]
    const blob = new Blob([rows.map((row) => row.map(csvCell).join(",")).join("\n")], { type: "text/csv;charset=utf-8" })
    const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "attendance.csv"; link.click(); URL.revokeObjectURL(link.href)
  }

  return <main className="flex-1 bg-muted/20 p-4 sm:p-6"><div className="mx-auto max-w-7xl space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">Attendance</h1><p className="text-sm text-muted-foreground">Check-ins and check-outs generated by mobile GPS events.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => refresh()}><RefreshCw /> Refresh</Button><Button variant="outline" onClick={download} disabled={!filtered.length}><Download /> Export CSV</Button></div></div>
    {error && <ApiError message={error} />}
    <div className="flex items-center gap-3"><label className="text-sm font-medium">Filter date</label><Input type="date" className="w-48" value={date} onChange={(event) => setDate(event.target.value)} />{date && <Button variant="ghost" onClick={() => setDate("")}>Clear</Button>}</div>
    <Card className="overflow-hidden">{loading ? <ApiLoading label="Loading attendance…" /> : <Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Field user</TableHead><TableHead>Check in</TableHead><TableHead>Check out</TableHead><TableHead>Duration</TableHead><TableHead>Area</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{filtered.map((record) => <TableRow key={record.id}><TableCell>{record.date}</TableCell><TableCell><div className="font-medium">{record.user?.name || "Unknown user"}</div><div className="text-xs text-muted-foreground">{record.user?.employeeCode}</div></TableCell><TableCell>{time(record.checkIn?.timestamp)}</TableCell><TableCell>{time(record.checkOut?.timestamp)}</TableCell><TableCell>{Math.floor(record.durationMinutes / 60)}h {record.durationMinutes % 60}m</TableCell><TableCell>{record.area || "—"}</TableCell><TableCell><Badge variant={record.status === "Late" || record.status === "Absent" ? "warning" : "success"}>{record.status}</Badge></TableCell></TableRow>)}</TableBody></Table>}
      {!loading && !filtered.length && <p className="p-10 text-center text-sm text-muted-foreground">No attendance records match this date.</p>}
    </Card>
  </div></main>
}
