"use client"

import { useState } from "react"
import { ChevronLeft, ChevronRight, Clock3, Crosshair, Flag, LocateFixed, MapPin, Navigation, RefreshCw, Route, Satellite } from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"

const points = [
  { time: "8:42 AM", area: "Main Boulevard, Gulberg III", detail: "Checked in", type: "start" },
  { time: "9:05 AM", area: "Liberty Market", detail: "Moving · 2.3 km", type: "move" },
  { time: "9:41 AM", area: "MM Alam Road", detail: "Stopped for 18 minutes", type: "stop" },
  { time: "10:12 AM", area: "Mini Market", detail: "Retail visit submitted", type: "activity" },
  { time: "10:48 AM", area: "Jail Road", detail: "Moving · 4.1 km", type: "move" },
  { time: "11:26 AM", area: "Shadman Market", detail: "Stopped for 26 minutes", type: "stop" },
  { time: "12:03 PM", area: "Mall Road", detail: "Moving · 3.8 km", type: "move" },
  { time: "12:34 PM", area: "Anarkali", detail: "Latest reported location", type: "end" },
]

export function LocationHistory() {
  const [user, setUser] = useState("Ahmed Raza"); const [date, setDate] = useState("2026-07-21"); const [start, setStart] = useState("08:00"); const [end, setEnd] = useState("18:00"); const [page, setPage] = useState(1)
  const pageSize = 5; const pageCount = Math.ceil(points.length / pageSize); const visible = points.slice((page - 1) * pageSize, page * pageSize)
  return <main className="flex-1 bg-muted/25 p-4 sm:p-6 xl:p-8"><div className="mx-auto max-w-[1600px] space-y-5"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-semibold tracking-tight">Location history</h1><p className="mt-1 text-sm text-muted-foreground">Review a simplified route for one user and selected date.</p></div><Badge variant="outline" className="w-fit"><Satellite /> 48 GPS updates loaded</Badge></div>
    <Card className="rounded-xl shadow-none"><CardContent className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-[1.3fr_1fr_1fr_1fr_auto]"><label className="text-xs text-muted-foreground">Field user<select value={user} onChange={(event) => setUser(event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border bg-background px-3 text-sm text-foreground"><option>Ahmed Raza</option><option>Sara Khan</option><option>Bilal Ahmed</option><option>Ayesha Malik</option></select></label><label className="text-xs text-muted-foreground">Date<Input type="date" value={date} onChange={(event) => setDate(event.target.value)} className="mt-1.5 h-10" /></label><label className="text-xs text-muted-foreground">Start time<Input type="time" value={start} onChange={(event) => setStart(event.target.value)} className="mt-1.5 h-10" /></label><label className="text-xs text-muted-foreground">End time<Input type="time" value={end} onChange={(event) => setEnd(event.target.value)} className="mt-1.5 h-10" /></label><Button className="self-end" size="lg"><RefreshCw /> Load history</Button></CardContent></Card>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Clock3} label="Total tracked duration" value="3h 52m" /><Metric icon={Flag} label="First location" value="Gulberg III" /><Metric icon={MapPin} label="Last location" value="Anarkali" /><Metric icon={Crosshair} label="GPS updates" value="48 points" /></section>
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.65fr)_minmax(320px,0.75fr)]"><Card className="overflow-hidden rounded-xl shadow-none"><CardContent className="p-0"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">Route map</h2><p className="mt-1 text-xs text-muted-foreground">{user} · {date} · {start}–{end}</p></div><Badge variant="secondary">Simplified route</Badge></div><div className="relative h-[520px] overflow-hidden bg-[#edf0eb]"><div className="absolute inset-0 opacity-60 [background-image:linear-gradient(#d8ddd5_1px,transparent_1px),linear-gradient(90deg,#d8ddd5_1px,transparent_1px)] [background-size:44px_44px]" /><div className="absolute left-[8%] top-[52%] h-9 w-[90%] -rotate-6 bg-white/80" /><div className="absolute left-[48%] top-[-10%] h-[120%] w-8 rotate-[16deg] bg-white/80" /><svg className="absolute inset-0 size-full" viewBox="0 0 800 500" preserveAspectRatio="none"><path d="M120 390 C170 330, 210 355, 260 290 S350 220, 420 260 S500 345, 560 270 S630 165, 700 120" fill="none" stroke="white" strokeWidth="12" strokeLinecap="round" /><path d="M120 390 C170 330, 210 355, 260 290 S350 220, 420 260 S500 345, 560 270 S630 165, 700 120" fill="none" stroke="#171717" strokeWidth="4" strokeLinecap="round" strokeDasharray="8 7" /></svg>{[{ left: "15%", top: "78%", label: "Start", className: "bg-emerald-500" }, { left: "33%", top: "56%", label: "2", className: "bg-neutral-900" }, { left: "53%", top: "52%", label: "3", className: "bg-neutral-900" }, { left: "70%", top: "45%", label: "4", className: "bg-neutral-900" }, { left: "87%", top: "24%", label: "End", className: "bg-red-500" }].map((point) => <span key={point.label} className={`absolute flex size-8 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border-2 border-white text-[9px] font-bold text-white shadow-lg ${point.className}`} style={{ left: point.left, top: point.top }}>{point.label}</span>)}<div className="absolute bottom-4 left-4 rounded-lg border bg-white/95 px-3 py-2 text-[11px] shadow-sm"><p className="font-medium">Route simplified for display</p><p className="mt-0.5 text-muted-foreground">48 raw updates · 8 meaningful points</p></div><div className="absolute right-4 top-4 flex flex-col gap-2"><Button variant="outline" size="icon" className="bg-white"><LocateFixed /></Button><Button variant="outline" size="icon" className="bg-white"><Navigation /></Button></div></div></CardContent></Card>
      <Card className="rounded-xl shadow-none"><CardContent className="p-0"><div className="border-b px-5 py-4"><h2 className="font-semibold">Location timeline</h2><p className="mt-1 text-xs text-muted-foreground">Meaningful points only</p></div><div className="p-5"><div className="relative ml-3 border-l pl-6">{visible.map((point) => <div key={`${point.time}-${point.area}`} className="relative pb-7 last:pb-0"><span className={`absolute -left-[31px] top-1 size-3 rounded-full border-2 border-white ring-1 ring-border ${point.type === "start" ? "bg-emerald-500" : point.type === "end" ? "bg-red-500" : "bg-neutral-900"}`} /><div className="flex justify-between gap-2"><p className="text-sm font-medium">{point.area}</p><span className="whitespace-nowrap text-xs text-muted-foreground">{point.time}</span></div><p className="mt-1 text-xs text-muted-foreground">{point.detail}</p></div>)}</div><div className="mt-5 flex items-center justify-between border-t pt-4"><span className="text-xs text-muted-foreground">Page {page} of {pageCount}</span><div className="flex gap-2"><Button variant="outline" size="icon-sm" disabled={page === 1} onClick={() => setPage((p) => p - 1)}><ChevronLeft /></Button><Button variant="outline" size="icon-sm" disabled={page === pageCount} onClick={() => setPage((p) => p + 1)}><ChevronRight /></Button></div></div></div></CardContent></Card></section>
    <div className="flex items-start gap-2 rounded-xl border bg-background p-4 text-xs text-muted-foreground"><Route className="mt-0.5 size-4 shrink-0" /><p>Large location histories are simplified before rendering. The complete coordinate set should be requested in pages from the location-history API and retained for audit or export without sending every point to the map at once.</p></div>
  </div></main>
}

function Metric({ icon: Icon, label, value }: { icon: typeof Clock3; label: string; value: string }) { return <Card className="rounded-xl shadow-none"><CardContent className="flex items-center gap-3 p-4"><span className="flex size-9 items-center justify-center rounded-lg bg-muted"><Icon className="size-4" /></span><div><p className="font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card> }
